name: PostTagsController
modelClass: EEV\Blog\Models\PostTag
form: $/eev/blog/models/posttag/fields.yaml
defaultRedirect: eev/blog/posttagscontroller
create:
    title: 'eev.blog::lang.creating'
    redirect: 'eev/blog/posttagscontroller/update/:id'
    redirectClose: eev/blog/posttagscontroller
    flashSave: eev.blog::lang.record_has_been_saved
update:
    title: 'eev.blog::lang.updating'
    redirect: eev/blog/posttagscontroller
    redirectClose: eev/blog/posttagscontroller
    flashSave: eev.blog::lang.record_has_been_saved
    flashDelete: eev.blog::lang.record_has_been_deleted
preview:
    title: 'eev.blog::lang.preview'
