title: PostsController
modelClass: EEV\Blog\Models\Post
list: $/eev/blog/models/post/columns.yaml
recordUrl: 'eev/blog/postscontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: ''
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
