title: PostCategoriesController
modelClass: EEV\Blog\Models\PostCategory
list: $/eev/blog/models/postcategory/columns.yaml
recordUrl: 'eev/blog/postcategoriescontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: 1
treeExpanded: 1
filter: config_filter.yaml
