# ===================================
# Filter Scope Definitions
# ===================================

scopes:

  statuses:
    label: 'eev.blog::lang.status'
    type: group
    conditions: status in (:filtered)
    options:
      published: 'eev.blog::lang.statuses.published'
      draft: 'eev.blog::lang.statuses.draft'
      disabled: 'eev.blog::lang.statuses.disabled'