# ===================================
# Filter Scope Definitions
# ===================================

scopes:

  authors:
    label: 'eev.blog::lang.user'
    modelClass: Backend\Models\User
    conditions: user_id in (:filtered)
    nameFrom: nameWithEmail

  posts:
    label: 'eev.blog::lang.posts'
    modelClass: EEV\Blog\Models\Post
    conditions: post_id in (:filtered)
    nameFrom: title

  approved:
    label: 'eev.blog::lang.is_moderated'
    type: switch
    conditions:
      - is_moderated <> true
      - is_moderated = true